#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

libs-$(CONFIG_LIB_USB) += libusbdrivers
libusbdrivers: libsel4 $(libc) libplatsupport common libsel4sync

ifeq ($(CONFIG_LIB_LWIP),y)
libusbdrivers: liblwip
endif
